"""The Memo Generator (spec agent #14, SM3): persists the final verified
thesis as a real markdown artifact — a downloadable file, not just chat
text.

Deterministic, not an LlmAgent — by the time this runs the thesis has
already been drafted (Synthesis), red-teamed (Critic/Refiner), verified
(Groundedness Verifier), and gate-cleared (HITL Gate), and the
Orchestrator's own instruction already forbids paraphrasing it when
presenting it in chat. Regenerating it through another LLM call here
would reintroduce exactly the risk that whole chain exists to remove,
for one more API call on top of an already-tight free-tier quota. Same
reasoning as reconciliation.py: where correctness matters more than
phrasing, use code (CLAUDE.md principle 1, extended to memo generation).

save_memo is called by the Orchestrator itself — never wired into
full_analysis_pipeline, and only AFTER an auto-approval or a human
approval, never after a rejection. A memo saved before the HITL Gate
decides (or from inside the pipeline, before the gate even runs) would
persist a rejected analysis to disk before a human ever saw it,
directly contradicting the reject behavior verified in Stage 5 Part B
(withhold the analysis, don't save to memory). Confirmed against
google/adk/tools/agent_tool.py that ArtifactService — unlike
MemoryService — IS forwarded across the AgentTool boundary via
ForwardingArtifactService, so this one tool could technically survive
being called from inside the pipeline without the boundary eating it;
it still doesn't live there, for the separate before-the-gate-decides
reason above. See principle 18 for the full three-service comparison
(state copied, artifacts forwarded, memory and long-running pauses not).
"""

import json
import re
from datetime import datetime, timezone

from google.adk.tools.tool_context import ToolContext
from google.genai import types

from argus.state_keys import (
    ANALYSIS_RECONCILED,
    DRAFT_THESIS,
    EVIDENCE_FILINGS,
    META_GROUNDEDNESS,
    META_HUMAN,
)
from argus.tools.memory import extract_entity_name

_SLUG_RE = re.compile(r"[^a-z0-9]+")


def _parse_state_json(raw) -> dict:
    if isinstance(raw, dict):
        return raw
    try:
        return json.loads(raw) if raw else {}
    except (json.JSONDecodeError, TypeError):
        return {}


def memo_filename(entity: str, generated_at: datetime) -> str:
    """Builds a stable, readable artifact filename, e.g.
    'memo_acme_corp_2026-08-01.md'."""
    slug = _SLUG_RE.sub("_", entity.strip().lower()).strip("_") or "unknown"
    return f"memo_{slug}_{generated_at.strftime('%Y-%m-%d')}.md"


def build_memo(
    entity: str,
    thesis: str,
    groundedness: float | None,
    human_decision: dict,
    contradictions_count: int,
    generated_at: datetime,
) -> str:
    """Assembles the memo's markdown. The thesis is copied VERBATIM — this
    only wraps it in a metadata header and a provenance footer, never
    rewrites a word of it.
    """
    score = f"{groundedness:.4f}" if isinstance(groundedness, (int, float)) else "unknown"
    decision = human_decision.get("decision", "unknown") if human_decision else "unknown"
    reason = human_decision.get("reason") if human_decision else None
    approval_line = decision + (f" — {reason}" if reason else "")
    thesis_body = thesis.strip() if thesis and thesis.strip() else "(no thesis available)"

    return (
        f"# ARGUS Due-Diligence Memo: {entity}\n\n"
        f"| | |\n"
        f"|---|---|\n"
        f"| Generated | {generated_at.strftime('%Y-%m-%d %H:%M UTC')} |\n"
        f"| Groundedness score | {score} |\n"
        f"| Release decision | {approval_line} |\n"
        f"| Cross-source contradictions found | {contradictions_count} |\n\n"
        f"---\n\n"
        f"{thesis_body}\n\n"
        f"---\n\n"
        f"*Sources: ARGUS mock filings, market, and sentiment data for {entity}. "
        f"Generated by ARGUS (Autonomous Reasoning & Grounded Understanding "
        f"System). This is analysis, not investment advice.*\n"
    )


async def save_memo(tool_context: ToolContext) -> dict:
    """Call this once, right after presenting an auto-approved or
    human-approved analysis — never after a rejection. Saves the final
    verified thesis as a real markdown file (a downloadable artifact),
    built entirely from this session's own state. Takes no arguments.

    Returns:
        dict with "saved" (bool) and "filename" if successful — mention
        the filename to the user in one short line. "saved": false is
        safe to ignore, same as remember_finding.
    """
    filings = _parse_state_json(tool_context.state.get(EVIDENCE_FILINGS))
    entity = extract_entity_name(filings)
    if entity is None:
        return {"saved": False}

    reconciled = _parse_state_json(tool_context.state.get(ANALYSIS_RECONCILED))
    contradictions_count = len(reconciled.get("contradictions", []))

    thesis = tool_context.state.get(DRAFT_THESIS, "")
    groundedness = tool_context.state.get(META_GROUNDEDNESS)
    human_decision = tool_context.state.get(META_HUMAN) or {}
    generated_at = datetime.now(timezone.utc)

    markdown = build_memo(
        entity, thesis, groundedness, human_decision, contradictions_count, generated_at
    )
    filename = memo_filename(entity, generated_at)

    version = await tool_context.save_artifact(
        filename,
        types.Part.from_bytes(data=markdown.encode("utf-8"), mime_type="text/markdown"),
    )
    return {"saved": True, "filename": filename, "version": version}
